<a href="https://colab.research.google.com/github/Chiranjeevi2001/introToDeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


##00 PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

In [3]:
# creating tensors
#scalar
scalar  = torch.tensor(73)
print(scalar.shape)

torch.Size([])


In [4]:
scalar.ndim

0

In [5]:
# Get Tensor back as Python int
scalar.item()

73

In [6]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7,8],
                       [1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor([[[2,3], [4,5]],
                       [[2,3],[10, 19]]])
TENSOR

tensor([[[ 2,  3],
         [ 4,  5]],

        [[ 2,  3],
         [10, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

## random tensor

In [15]:
random_tensor = torch.rand(3,4,2,10)
random_tensor

tensor([[[[0.2712, 0.0821, 0.2847, 0.4411, 0.3089, 0.0925, 0.5292, 0.5522,
           0.4825, 0.2551],
          [0.5331, 0.6219, 0.5308, 0.9480, 0.2321, 0.3331, 0.9807, 0.5493,
           0.7142, 0.1305]],

         [[0.8845, 0.8937, 0.0577, 0.1199, 0.5397, 0.2967, 0.0983, 0.6179,
           0.8028, 0.8998],
          [0.8255, 0.6205, 0.1350, 0.6204, 0.8306, 0.4171, 0.4246, 0.1407,
           0.2059, 0.5459]],

         [[0.0578, 0.5174, 0.5809, 0.6528, 0.2367, 0.5940, 0.7321, 0.8629,
           0.3508, 0.6953],
          [0.4205, 0.8836, 0.4235, 0.1754, 0.1564, 0.2666, 0.5312, 0.3337,
           0.8688, 0.5684]],

         [[0.2593, 0.6356, 0.5462, 0.9504, 0.5644, 0.9227, 0.9570, 0.7560,
           0.3107, 0.4267],
          [0.1421, 0.3546, 0.9023, 0.3554, 0.7997, 0.2680, 0.9246, 0.2666,
           0.0609, 0.2060]]],


        [[[0.9483, 0.9525, 0.3014, 0.6027, 0.8055, 0.7361, 0.2553, 0.4007,
           0.5363, 0.9527],
          [0.4430, 0.7934, 0.5548, 0.7934, 0.6777, 0.7462, 0.51

In [16]:
#creating a tensor with the same size as that of an image
random_image_size_tensor = torch.rand(size=(224,224,3) )#height, width and color channel (rgb)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
random_tensor = torch.rand(3,3)
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# Use torch.arange()

one_to_ten = torch.arange(0,10.1,0.1) # start (inclusive), end(exclusive) and the step.
one_to_ten, one_to_ten.shape

(tensor([ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,  0.7000,
          0.8000,  0.9000,  1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,
          1.6000,  1.7000,  1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,
          2.4000,  2.5000,  2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,
          3.2000,  3.3000,  3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,
          4.0000,  4.1000,  4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,
          4.8000,  4.9000,  5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,
          5.6000,  5.7000,  5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,
          6.4000,  6.5000,  6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,
          7.2000,  7.3000,  7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,
          8.0000,  8.1000,  8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,
          8.8000,  8.9000,  9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,
          9.6000,  9.7000,  

In [22]:
# Creating tensor-like

ten_zeros = torch.zeros_like(input = one_to_ten) #create a zeros tensor with the same shape as that of one_to_ten tensor
ten_zeros, ten_zeros.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]),
 torch.Size([101]))

## Tensor datatypes

In [23]:
float32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None, #datatype of tensor
                              device = None, #on which device the tensor is stored, default = "cpu"
                              requires_grad = False # track the gradients with tensor operations
                              )

In [24]:
float32_tensor, float32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [27]:
int32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float32_tensor * int32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)

In [29]:
int32_tensor.dtype, float32_tensor.dtype, float16_tensor.dtype # getting the datatype

(torch.int32, torch.float32, torch.float16)

In [30]:
int32_tensor.shape, float32_tensor.shape, float16_tensor.shape # getting the shape

(torch.Size([3]), torch.Size([3]), torch.Size([3]))

In [31]:
int32_tensor.device, float32_tensor.device, float16_tensor.device # get the device

(device(type='cpu'), device(type='cpu'), device(type='cpu'))

In [33]:
gpu_tensor = int32_tensor.to("cpu")

In [34]:
gpu_tensor.device

device(type='cpu')

## Manipulating Tensors (Tensor Operations)

1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [35]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10 # adds 10 to every element

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor/5

tensor([0.2000, 0.4000, 0.6000])

In [38]:
tensor-10

tensor([-9, -8, -7])

In [39]:
# Inbuilt functions for tensor

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication (most common tensor operation)

In [40]:
%%time
torch.matmul(tensor, tensor) ## works like a dot product for 1-d tensors

CPU times: user 189 µs, sys: 35 µs, total: 224 µs
Wall time: 345 µs


tensor(14)

In [41]:
# calculating dot product manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 501 µs, sys: 916 µs, total: 1.42 ms
Wall time: 1.35 ms


### One of the most common errors in deep learning: Shape Errors

Inner dimensions during matrix multiplication should match

* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work

The resulting matrix will have the dimensions of the outter dimensions.

In [45]:
torch.matmul(torch.rand(3,2), torch.rand(2,2)).shape

torch.Size([3, 2])