<a href="https://colab.research.google.com/github/Chiranjeevi2001/introToDeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


##00 PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

In [3]:
# creating tensors
#scalar
scalar  = torch.tensor(73)
print(scalar.shape)

torch.Size([])


In [4]:
scalar.ndim

0

In [5]:
# Get Tensor back as Python int
scalar.item()

73

In [6]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7,8],
                       [1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor([[[2,3], [4,5]],
                       [[2,3],[10, 19]]])
TENSOR

tensor([[[ 2,  3],
         [ 4,  5]],

        [[ 2,  3],
         [10, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

## random tensor

In [15]:
random_tensor = torch.rand(3,4,2,10)
random_tensor

tensor([[[[0.4283, 0.7909, 0.9071, 0.4012, 0.0388, 0.4062, 0.9613, 0.6362,
           0.1859, 0.9505],
          [0.4623, 0.7537, 0.9531, 0.1071, 0.4648, 0.3920, 0.2726, 0.0066,
           0.0095, 0.7693]],

         [[0.2735, 0.0860, 0.9752, 0.9752, 0.1954, 0.7498, 0.8212, 0.9680,
           0.8681, 0.5909],
          [0.0248, 0.6220, 0.1405, 0.5422, 0.3025, 0.6789, 0.2318, 0.6215,
           0.6778, 0.8041]],

         [[0.6020, 0.7745, 0.9032, 0.5595, 0.3472, 0.7646, 0.5514, 0.6546,
           0.2868, 0.0890],
          [0.2277, 0.7566, 0.6872, 0.4006, 0.4843, 0.5380, 0.4531, 0.9011,
           0.7733, 0.3654]],

         [[0.1029, 0.3646, 0.8285, 0.7113, 0.4947, 0.8337, 0.1713, 0.3146,
           0.3632, 0.6205],
          [0.9514, 0.0574, 0.2000, 0.1778, 0.0124, 0.7789, 0.8520, 0.2794,
           0.7262, 0.3131]]],


        [[[0.6477, 0.3651, 0.7794, 0.1170, 0.7667, 0.1666, 0.2486, 0.1812,
           0.0314, 0.8399],
          [0.1338, 0.3965, 0.5600, 0.9536, 0.5831, 0.4933, 0.72

In [16]:
#creating a tensor with the same size as that of an image
random_image_size_tensor = torch.rand(size=(224,224,3) )#height, width and color channel (rgb)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
random_tensor = torch.rand(3,3)
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# Use torch.arange()

one_to_ten = torch.arange(0,10.1,0.1) # start (inclusive), end(exclusive) and the step.
one_to_ten, one_to_ten.shape

(tensor([ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,  0.7000,
          0.8000,  0.9000,  1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,
          1.6000,  1.7000,  1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,
          2.4000,  2.5000,  2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,
          3.2000,  3.3000,  3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,
          4.0000,  4.1000,  4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,
          4.8000,  4.9000,  5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,
          5.6000,  5.7000,  5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,
          6.4000,  6.5000,  6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,
          7.2000,  7.3000,  7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,
          8.0000,  8.1000,  8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,
          8.8000,  8.9000,  9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,
          9.6000,  9.7000,  

In [22]:
# Creating tensor-like

ten_zeros = torch.zeros_like(input = one_to_ten) #create a zeros tensor with the same shape as that of one_to_ten tensor
ten_zeros, ten_zeros.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]),
 torch.Size([101]))

## Tensor datatypes

In [23]:
float32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None, #datatype of tensor
                              device = None, #on which device the tensor is stored, default = "cpu"
                              requires_grad = False # track the gradients with tensor operations
                              )

In [24]:
float32_tensor, float32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [27]:
int32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float32_tensor * int32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)

In [29]:
int32_tensor.dtype, float32_tensor.dtype, float16_tensor.dtype # getting the datatype

(torch.int32, torch.float32, torch.float16)

In [30]:
int32_tensor.shape, float32_tensor.shape, float16_tensor.shape # getting the shape

(torch.Size([3]), torch.Size([3]), torch.Size([3]))

In [31]:
int32_tensor.device, float32_tensor.device, float16_tensor.device # get the device

(device(type='cpu'), device(type='cpu'), device(type='cpu'))

In [32]:
gpu_tensor = int32_tensor.to("cpu")

In [33]:
gpu_tensor.device

device(type='cpu')

## Manipulating Tensors (Tensor Operations)

1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [34]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10 # adds 10 to every element

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor/5

tensor([0.2000, 0.4000, 0.6000])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
# Inbuilt functions for tensor

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication (most common tensor operation)

In [39]:
%%time
torch.matmul(tensor, tensor) ## works like a dot product for 1-d tensors

CPU times: user 89 µs, sys: 13 µs, total: 102 µs
Wall time: 107 µs


tensor(14)

In [40]:
# calculating dot product manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.08 ms, sys: 11 µs, total: 1.09 ms
Wall time: 1.1 ms


### One of the most common errors in deep learning: Shape Errors

Inner dimensions during matrix multiplication should match

* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work

The resulting matrix will have the dimensions of the outter dimensions.

In [41]:
torch.matmul(torch.rand(3,2), torch.rand(2,2)).shape

torch.Size([3, 2])

In [42]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# transpose any one of the matrices to fix the shape issue
torch.mm(tensor_A.mT, tensor_B)  ## torch.mm == torch.matmul

tensor([[ 76, 103],
        [100, 136]])

## Tensor Aggregation functions
(min, max, mean, sum, etc.)

In [43]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [45]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [46]:
x.dtype

torch.int64

In [47]:
# mean function does not work on int64 (long) datatype it requires float32 or complex datatypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [48]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the position of the max and min (positional max and min) in tensors

In [49]:
x.argmin() # returns 0-based index of the minimum element in the tensor

tensor(0)

In [50]:
x.argmax() # returns 0-based index of the maximum element in the tensor

tensor(9)