<a href="https://colab.research.google.com/github/Chiranjeevi2001/introToDeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


##00 PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

In [3]:
# creating tensors
#scalar
scalar  = torch.tensor(73)
print(scalar.shape)

torch.Size([])


In [4]:
scalar.ndim

0

In [5]:
# Get Tensor back as Python int
scalar.item()

73

In [6]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7,8],
                       [1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor([[[2,3], [4,5]],
                       [[2,3],[10, 19]]])
TENSOR

tensor([[[ 2,  3],
         [ 4,  5]],

        [[ 2,  3],
         [10, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

## random tensor

In [15]:
random_tensor = torch.rand(3,4,2,10)
random_tensor

tensor([[[[0.5231, 0.0850, 0.0764, 0.2092, 0.8809, 0.2281, 0.4649, 0.9995,
           0.9628, 0.4015],
          [0.8229, 0.2823, 0.9910, 0.7103, 0.2853, 0.1560, 0.6138, 0.5293,
           0.1963, 0.2693]],

         [[0.8101, 0.4455, 0.5099, 0.9900, 0.1903, 0.4865, 0.9235, 0.6537,
           0.3500, 0.1682],
          [0.1951, 0.1827, 0.6855, 0.7922, 0.9898, 0.5076, 0.3826, 0.2930,
           0.8330, 0.5142]],

         [[0.2349, 0.5582, 0.3630, 0.1828, 0.3114, 0.2917, 0.2799, 0.3457,
           0.5431, 0.8289],
          [0.9372, 0.0641, 0.9224, 0.8241, 0.3985, 0.6924, 0.9194, 0.2659,
           0.0985, 0.2578]],

         [[0.2294, 0.4196, 0.0305, 0.1580, 0.8203, 0.9717, 0.2733, 0.3809,
           0.8339, 0.5325],
          [0.6675, 0.1334, 0.3734, 0.2462, 0.9598, 0.6300, 0.2060, 0.1735,
           0.3026, 0.1267]]],


        [[[0.3882, 0.4909, 0.9293, 0.2920, 0.1652, 0.4578, 0.1139, 0.1599,
           0.5939, 0.5628],
          [0.8952, 0.8631, 0.5901, 0.8481, 0.1167, 0.3569, 0.05

In [16]:
#creating a tensor with the same size as that of an image
random_image_size_tensor = torch.rand(size=(224,224,3) )#height, width and color channel (rgb)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
random_tensor = torch.rand(3,3)
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# Use torch.arange()

one_to_ten = torch.arange(0,10.1,0.1) # start (inclusive), end(exclusive) and the step.
one_to_ten, one_to_ten.shape

(tensor([ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,  0.7000,
          0.8000,  0.9000,  1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,
          1.6000,  1.7000,  1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,
          2.4000,  2.5000,  2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,
          3.2000,  3.3000,  3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,
          4.0000,  4.1000,  4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,
          4.8000,  4.9000,  5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,
          5.6000,  5.7000,  5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,
          6.4000,  6.5000,  6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,
          7.2000,  7.3000,  7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,
          8.0000,  8.1000,  8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,
          8.8000,  8.9000,  9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,
          9.6000,  9.7000,  

In [22]:
# Creating tensor-like

ten_zeros = torch.zeros_like(input = one_to_ten) #create a zeros tensor with the same shape as that of one_to_ten tensor
ten_zeros, ten_zeros.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]),
 torch.Size([101]))

## Tensor datatypes

In [23]:
float32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None, #datatype of tensor
                              device = None, #on which device the tensor is stored, default = "cpu"
                              requires_grad = False # track the gradients with tensor operations
                              )

In [24]:
float32_tensor, float32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [27]:
int32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float32_tensor * int32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)

In [29]:
int32_tensor.dtype, float32_tensor.dtype, float16_tensor.dtype # getting the datatype

(torch.int32, torch.float32, torch.float16)

In [30]:
int32_tensor.shape, float32_tensor.shape, float16_tensor.shape # getting the shape

(torch.Size([3]), torch.Size([3]), torch.Size([3]))

In [31]:
int32_tensor.device, float32_tensor.device, float16_tensor.device # get the device

(device(type='cpu'), device(type='cpu'), device(type='cpu'))

In [32]:
gpu_tensor = int32_tensor.to("cpu")

In [33]:
gpu_tensor.device

device(type='cpu')

## Manipulating Tensors (Tensor Operations)

1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [34]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10 # adds 10 to every element

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor/5

tensor([0.2000, 0.4000, 0.6000])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
# Inbuilt functions for tensor

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication (most common tensor operation)

In [39]:
%%time
torch.matmul(tensor, tensor) ## works like a dot product for 1-d tensors

CPU times: user 271 µs, sys: 54 µs, total: 325 µs
Wall time: 3.45 ms


tensor(14)

In [40]:
# calculating dot product manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 791 µs, sys: 1.16 ms, total: 1.95 ms
Wall time: 5.12 ms


### One of the most common errors in deep learning: Shape Errors

Inner dimensions during matrix multiplication should match

* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work

The resulting matrix will have the dimensions of the outter dimensions.

In [41]:
torch.matmul(torch.rand(3,2), torch.rand(2,2)).shape

torch.Size([3, 2])

In [42]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# transpose any one of the matrices to fix the shape issue
torch.mm(tensor_A.mT, tensor_B)  ## torch.mm == torch.matmul

tensor([[ 76, 103],
        [100, 136]])

## Tensor Aggregation functions
(min, max, mean, sum, etc.)

In [43]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [45]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [46]:
x.dtype

torch.int64

In [47]:
# mean function does not work on int64 (long) datatype it requires float32 or complex datatypes
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [48]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the position of the max and min (positional max and min) in tensors

In [49]:
x.argmin() # returns 0-based index of the minimum element in the tensor

tensor(0)

In [50]:
x.argmax() # returns 0-based index of the maximum element in the tensor

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape - modifying the shape of an input tensor
* View - return a view of an input tensor of a certain shape but keep the same memory of the original tensor
* Stack - concatenates a sequence of tensors along a new dimension (vstack and hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target vector
* Permute - return a view of the input dimensions permuted (swapped) in a certain way

In [51]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [52]:
# Add an extra dimension
# new dimensions should be compatible with the original dimension (product of new dimensions == product of old dimensions)
x_reshape = x.reshape(shape=(2,5))
x_reshape.shape

torch.Size([2, 5])

In [53]:
 # Change the view
 # manipulating z will also change x, since they share the same memory
z = x.view(5,2)
z, z.shape
z[:,0] = 5
z,x

(tensor([[ 5.,  2.],
         [ 5.,  4.],
         [ 5.,  6.],
         [ 5.,  8.],
         [ 5., 10.]]),
 tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]))

In [54]:
# stacking the tensors

x_stacked1 = torch.stack([x,x,x,x], dim=0)
x_stacked2 = torch.stack([x,x,x,x], dim=1)
x_stacked1, x_stacked2

(tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
         [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
         [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
         [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]]),
 tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 5.,  5.,  5.,  5.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 5.,  5.,  5.,  5.],
         [ 8.,  8.,  8.,  8.],
         [ 5.,  5.,  5.,  5.],
         [10., 10., 10., 10.]]))

In [55]:
# squeeze and unsqueeze
x = torch.zeros(2,1,2,1,2)
x.size(), x

(torch.Size([2, 1, 2, 1, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [56]:
y = torch.squeeze(x)
y.size(), y # all one dimensions of x are removed

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [57]:
# unsqueeze
y = x.unsqueeze(dim= 3) # one dimension is added at the 3rd dimension
y.shape, y

(torch.Size([2, 1, 2, 1, 1, 2]),
 tensor([[[[[[0., 0.]]],
 
 
           [[[0., 0.]]]]],
 
 
 
 
         [[[[[0., 0.]]],
 
 
           [[[0., 0.]]]]]]))

In [58]:
# permute

x = torch.rand(size=(224,224,3)) # 0dim:224, 1dim:224, 2dim:3

x.shape

torch.Size([224, 224, 3])

In [59]:
y = x.permute(2, 0, 1) # 0dim_new = 2dim_old = 3, 1dim_new = 0dim_old = 224, 2dim_new = 1dim_old = 224 (dimensions are remapped)
y.shape

torch.Size([3, 224, 224])

In [60]:
x[0,0,0]

tensor(0.0328)

In [61]:
y[0,0,0]

tensor(0.0328)

In [62]:
x[0,0,0] = 5

In [63]:
y[0,0,0] #shares the same memory as x

tensor(5.)

## Indexing (selecting data from tensors)

In [64]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
# Indexing on our new tensor

x[0] # indexing on the 0th dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0][0], x[0][2] # indexing on the 1st dimension

(tensor([1, 2, 3]), tensor([7, 8, 9]))

In [67]:
x[0][0][0], x[0][2][2] # indexing on the 3rd dimension

(tensor(1), tensor(9))

In [68]:
# use ":" to select all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [69]:
# Get all values of the 0th and 1st dimension, but only index 1 of 2nd dimesion

x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
x[:,1,1]

tensor([5])

In [71]:
x[:,:,2]

tensor([[3, 6, 9]])

In [72]:
x.ndim

3

## Numpy

In [76]:
# numpy array to pytorch tensor
import numpy as np
array = np.arange(1.,10.)

tensor = torch.from_numpy(array)

array.dtype, tensor.dtype # float 64 stays as float64


(dtype('float64'), torch.float64)

In [77]:
# to convert to type float32
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [80]:
#change the value of array

array = array+1

array, tensor # array and tensor use different memory

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [82]:
# Tensor to numpy array

tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor.dtype, numpy_tensor.dtype ## again, default datatype of float 32 stays

(torch.float32, dtype('float32'))

In [84]:
# change the tensor

tensor = tensor+1

tensor, numpy_tensor # different memory

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility: trying to take random out of randomness

To reduce randomness in neural networks, use **random seed**. It "flavours"the randomness

In [86]:
torch.rand(3,3) # gives a random number every time its run

tensor([[0.5416, 0.9146, 0.6875],
        [0.1471, 0.3507, 0.6684],
        [0.6551, 0.0638, 0.5000]])

In [89]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [92]:
# Random but reproducible tensors

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # set the manual seed each time the rand function is called
random_tensor_D = torch.rand(3,4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and pytorch objects on GPUs and making computations faster

In [94]:
torch.cuda.is_available()

False

In [95]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [96]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [99]:
# moving to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device # would give CUDA if connected to a GPU runtime

device(type='cpu')

## We cannot convert a Tensor which is on GPU to numpy
Bring tensor to cpu first

In [102]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_cpu.dtype

dtype('int64')